config/routes.rb
Rails.application.routes.draw do
  resources :menu_items
  resources :order_items
  resources :orders
  post 'order_items/:id/add' => "order_items#add_quantity", as: "order_item_add"
  post 'order_items/:id/reduce' => "order_items#reduce_quantity", as: "order_item_reduce"
  root 'menu_items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_assignments
  has_many :menu_items, through: :category_assignments

  validates :title, presence: true
end

app/models/category_assignment.rb
class CategoryAssignment < ApplicationRecord
  belongs_to :menu_item
  belongs_to :category

  validates :menu_item_id, :category_id, presence: true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  has_many :order_items
  has_many :category_assignments
  has_many :categories, through: :category_assignments

  # accepts_nested_attributes_for :category_assignments

  has_attached_file :menu_item_image,
    styles: {
      thumb: '100x100>',
      square: '200x200#',
      medium: '300x300>'
    },
    default_url: 'http://www.emoji.co.uk/files/mozilla-emojis/food-drink-mozilla/0.png'
end

app/models/order.rb
# class Order < ApplicationRecord
#   has_many :order_items
#   has_many :menu_items, through: :order_items
#
#   def subtotal
#     menu_item.price * quantity
#   end
#
#   def order_total
#     total = 0
#     order_items = OrderItem.where(in_order: true)
#     order_items.each do |order_item|
#       total = total (order_item.menu_item.price * order_item.quantity)
#     end
#     return total
#   end
#
# end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :menu_item
  # belongs_to :order

  def subtotal
    menu_item.price * quantity
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def create
  end
end

app/controllers/category_assignments_controller.rb
class CategoryAssignmentsController < ApplicationController
  def new
    # @category_assignment = CategoryAssigment.new
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    @menu_items = MenuItem.all
    @categories = Category.all
  end

  def show
    @menu_item = MenuItem.find(params[:id])
  end

  def new
    @menu_item = MenuItem.new
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)
    # @menu_item.category_assignments.build(params[:category_id])

    if @menu_item.save
      redirect_to @menu_item
    else
      render 'new'
    end
  end

  def update
    @menu_item = MenuItem.find(params[:id])

    if @menu_item.update(menu_item_params)
      redirect_to @menu_item
    else
      render 'edit'
    end
  end

  def destroy
    @menu_item = MenuItem.find(params[:id])
    @menu_item.destroy

    redirect_to menu_items_path
  end

  private
  def menu_item_params
    params.require(:menu_item).permit(:name, :description, :price, :category, :menu_item_image, category_assignments_attributes: [ :menu_item_id, :category_id ])
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def index
    @order_items = OrderItem.all
    @total = 0
    in_order_items = OrderItem.where(in_order: true)
    in_order_items.each do |order_item|
      @total = @total + (order_item.menu_item.price * order_item.quantity)
    end
  end

  def create
    @order_items = OrderItem.all
    @order_item = OrderItem.new(
                        in_order: true,
                        quantity: 1,
                        menu_item_id: params[:menu_item_id]
                      )
    if @order_item.save
      redirect_to '/order_items'
    end
  end

  def update
  end

  def destroy
    @order_item = OrderItem.find(params[:id])
    @order_item.destroy

    redirect_to order_items_path
  end

  def add_quantity
    @order_item = OrderItem.find(params[:id])
    @order_item.quantity += 1
    @order_item.save
    redirect_to '/order_items'
  end

  def reduce_quantity
    @order_item = OrderItem.find(params[:id])
    if @order_item.quantity > 1
      @order_item.quantity -= 1
    end
    @order_item.save
    redirect_to '/orders'
  end

  def add_tip
    @order_item
  end

  private

  def order_item_params
    params.require(:order_item).permit(:quantity, :in_order)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @order_items = OrderItem.all
    @total = 0
    in_order_items = OrderItem.where(in_order: true)
    in_order_items.each do |order_item|
      @total = @total + (order_item.menu_item.price * order_item.quantity)
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('banana.ico'), :rel => 'icon', :type => "image/x-icon" %>
    <title>Menu App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
       <img src="https://cdn.shopify.com/s/files/1/1061/1924/files/Banana_Emoji.png?9898922749706957214" style="width: 50px; height: 50px; margin: 10px;">
       <div class="navbar-item">
         <h1 class="title">Menu App</h1>
       </div>
     </div>
      <div class="navbar-menu is-active">
        <div class="navbar-end">
          <div class = "navbar-item"><%= link_to 'Home', root_path %></div>
          <div class = "navbar-item"><%= link_to 'View Order', order_items_path %></div>
        </div>
      </div>
    </nav>
    <hr>
    <section class="section">
    <%= yield %>
  </body>
</html>

app/views/menu_items/_form.html.erb
<%= form_for @menu_item do |form| %>

  <% if @menu_item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@menu_item.errors.count, "error") %> prohibited
        this menu item from being saved:
      </h2>
      <ul>
        <% @menu_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %>:
    <%= form.text_field :name %>
  </p>
  <br>
  <p>
    <%= form.label :description %>:
    <%= form.text_area :description %>
  </p>
  <br>
  <p>
    <%= form.label :price %>: $
    <%= form.number_field(:price, in: 2.5..30.0, :step => 0.25) %>
  </p>
  <br>
  <p>
    <%= form.fields_for :category_assignments do |form| %>
      <%= form.label :category %>
      <%= form.collection_select :category_id, Category.all, :id, :title, prompt: 'Select One' %>
      <%= hidden_field_tag :menu_item_id, @menu_item.id %>
    <% end %>
  </p>
  <br>
  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/menu_items/edit.html.erb
<h1 class="title">Edit the Menu Item</h1>

<%= render 'form' %>
<br>
<%= link_to 'Nevermind, go back to item', menu_item_path(@menu_item) %>

app/views/menu_items/index.html.erb
<h1 class="title">Menu Items by Category</h1>

<% @categories.each do |category| %>
  <h2 class="title"><%= category.title %>s</h2>
  <table class="table is-bordered">
    <tr>
      <th>Item</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
      <th></th>
    </tr>
    <% category.menu_items.each do |menu_item| %>
    <tr>
      <td><%= menu_item.name %></td>
      <td><%= menu_item.description %></td>
      <td>$<%= menu_item.price %></td>
      <td><%= link_to 'View Item', menu_item_path(menu_item) %></td>
      <td><%= button_to 'Add to cart', order_items_path(menu_item_id: menu_item.id) %></td>
    </tr>

    <% end %>
    </table>
  <% end %>



<%= link_to 'Add a Menu Item', new_menu_item_path %>

app/views/menu_items/new.html.erb
<h1 class="title">Create a New Menu Item</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/menu_items/show.html.erb
<h1 class="title"><%= @menu_item.name%> Menu</h1>

  <table class="table is-bordered">
    <tr>
      <th>Menu Item</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
      <th></th>
      <th></th>
    </tr>

    <tr>
      <td><%= @menu_item.name %></td>
      <td><%= @menu_item.description %></td>
      <td>$<%= @menu_item.price %></td>
      <td><%= @menu_item.categories.first.title %></td>
      <td><%= link_to 'Edit Item', edit_menu_item_path(@menu_item) %></td>
      <td><%= link_to 'Delete Item', menu_item_path(@menu_item),
              method: :delete,
              data: { confirm: 'Do you really want to delete this item?'} %></td>
    </tr>
  </table>

<%= link_to 'Back to Menu', root_path %>

app/views/order_items/index.html.erb
<h1 class="title">Order Items</h1>

<% if @order_items.count == 0 %>
  <p>Your order is empty.</p>
  <p>Get back to the Menu and add some food!</p>
<% else %>
  <table class="table is-bordered">
    <tr>
      <th>Menu Item</th>
      <th>Price</th>
      <th>Total for Item</th>
      <th>Item Count</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <% @order_items.each do |order_item| %>
        <tr>
          <td><%= MenuItem.find(order_item.menu_item_id).name %></td>
          <td>$ <%= (MenuItem.find(order_item.menu_item_id)).price%></td>
          <td>$ <%= order_item.subtotal %></td>
          <td><%= order_item.quantity %></td>
          <td><%= link_to 'Add one', order_item_add_path(:id => order_item), method: :post %></td>
          <td><%= link_to 'Remove one', order_item_reduce_path(:id => order_item), method: :post %></td>
          <td><%= link_to 'Remove from Cart', order_item_path(order_item),
                  method: :delete,
                  data: { confirm: 'Do you really want to not eat this?'} %></td>
        </tr>
    <% end %>
  </table>
    <p><strong>Order Total: $ <%= @total %></strong></p>
<% end %>
<br>

<br>
<%= link_to 'Back to Menu', root_path %>

app/views/orders/index.html.erb
<h1 class="title">Order Items</h1>

<% if @order_items.count == 0 %>
  <p>Your order is empty.</p>
  <p>Get back to the Menu and add some food!</p>
<% else %>
  <table class="table is-bordered">
    <tr>
      <th>Menu Item</th>
      <th>Price</th>
      <th>Total for Item</th>
      <th>Item Count</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <% @order_items.each do |order_item| %>
        <tr>
          <td><%= MenuItem.find(order_item.menu_item_id).name %></td>
          <td>$ <%= (MenuItem.find(order_item.menu_item_id)).price%></td>
          <td>$ <%= order_item.subtotal %></td>
          <td><%= order_item.quantity %></td>
          <td><%= link_to 'Add one', order_item_add_path(:id => order_item), method: :post %></td>
          <td><%= link_to 'Remove one', order_item_reduce_path(:id => order_item), method: :post %></td>
          <td><%= link_to 'Remove from Cart', order_item_path(order_item),
                  method: :delete,
                  data: { confirm: 'Do you really want to not eat this?'} %></td>
        </tr>
    <% end %>
  </table>
    <p><strong>Order Total: $ <%= @total %></strong></p>
<% end %>
<br>

<br>
<%= link_to 'Back to Menu', root_path %>